### PR TITLE
fixed 'Function has keyword-only arguments or annotations' error in p…

### PR DESCRIPTION
**Pull request by oeegor**
…ython 3.5

### CODE REVIEW

**Comment by tvavrys** [comment]
Could you tell me please how can I trigger it?

**Comment by oeegor** [comment]
for example
`@memoize
def foo(a=None):`

**Comment by oeegor** [comment]
Sorry, here is a correct example for python3 
```py
@memoize()
def foo(a: str=None)
     pass

foo()
# ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them```

**Comment by tvavrys** [comment]
Thanks.

**Pull request merged**
